---
kind: pipeline
type: docker
name: Release

trigger:
  branch:
    - main

steps:
  - name: Fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - echo "RELEASE_VERSION=$(git describe --tags --abbrev=0 | cut -c 2-)" | tee -a .env;

  - name: Validate and Test
    image: gsmlg/phoenix
    environment:
      HEX_MIRROR: "https://nexus.gsmlg.net/repository/hex-pm/"
      HEX_CDN: "https://nexus.gsmlg.net/repository/hex-pm/"
      MIX_ENV: test
    commands:
      - mix deps.get --only test
      - mix format --check-formatted
      - mix test

  - name: Release
    image: gsmlg/semantic-release
    environment:
      NPM_CONFIG_REGISTRY: "https://nexus.gsmlg.net/repository/npm-org/"
      MIX_ENV: prod
    commands:
      - semantic-release

  - name: Set web version
    image: gsmlg/curl
    commands:
      - echo WEB_VERSION=$(curl -s https://registry.npmjs.org/@gsmlg/website | jq -r '.["dist-tags"].latest') | tee -a .env

  - name: Publish
    image: plugins/docker
    settings:
      repo: docker.io/gsmlg/gsmlg.org
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD
      build_args_from_env:
        - RELEASE_VERSION
    commands:
      - source .env
      - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker
