---
kind: pipeline
type: docker
name: Release

steps:
  - name: Fetch
    image: alpine/git
    commands:
      - git fetch --tags

  - name: Validate and Test
    image: gsmlg/phoenix
    environment:
      MIX_ENV: test
    commands:
      - mix deps.get --only test
      - mix format --check-formatted
      - mix test

  - name: Release
    image: node:lts-alpine
    environment:
      MIX_ENV: prod
    commands:
      - npm i semantic-release "@semantic-release/changelog" "@semantic-release/git" "@semantic-release/exec"
      - npx semantic-release
