variables:
  DOCKER_REGISTRY: gsmlg.dev
  DOCKER_IMAGE_NAME: apps/gsmlg

include:
  - local: "/apps/gsmlg_commander/.gitlab-ci.yml"

stages: # List of stages for jobs, and their order of execution
  - test
  - release
  - build
  - publish

cache:
  - key:
      files:
        - mix.lock
    paths:
      - deps
      - _build

svc-unit-test:
  tags:
    - docker
    - linux
  stage: test
  image:
    name: ghcr.io/gsmlg-dev/phoenix:alpine
    entrypoint:
      - /bin/bash
      - "-c"
  rules:
    - changes:
        - "apps/gsmlg/**/*"
        - "apps/gsmlg_web/**/*"
        - "apps/gsmlg_admin_web/**/*"
        - "config/**/*"
        - "mix.*"
  variables:
    MIX_ENV: test
    GSMLG_UMBRELLA: "true"
  script:
    - mix deps.get
    - mix format --check-formatted
    - mix test apps/gsmlg/test
    - mix test apps/gsmlg_web/test
    - mix test apps/gsmlg_admin_web/test

svc-release:
  dependencies:
    - "svc-unit-test"
  tags:
    - docker
    - linux
  stage: release
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|beta|alpha)$/
      changes:
        - "apps/gsmlg/**/*"
        - "apps/gsmlg_web/**/*"
        - "apps/gsmlg_admin_web/**/*"
        - "config/**/*"
        - "mix.*"
  image: ghcr.io/gsmlg-dev/semantic-release:latest
  variables:
    MIX_ENV: prod
  script:
    - semantic-release
  artifacts:
    paths:
      - releaseVersion

svc-build:
  dependencies:
    - svc-release
  tags:
    - docker
    - linux
  stage: build
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|beta|alpha)$/
      changes:
        - "apps/gsmlg/**/*"
        - "apps/gsmlg_web/**/*"
        - "apps/gsmlg_admin_web/**/*"
        - "config/**/*"
        - "mix.*"
  image: ghcr.io/gsmlg-dev/phoenix:alpine
  variables:
    MIX_ENV: prod
  script:
    - mix deps.get
    - npm install
    - cd ${CI_PROJECT_DIR}/apps/gsmlg_admin_web && mix assets.deploy
    - cd ${CI_PROJECT_DIR}/apps/gsmlg_web && mix assets.deploy
    - cd ${CI_PROJECT_DIR}
    - ./update_version.sh "$(cat ${CI_PROJECT_DIR}/releaseVersion)"
    - mix release gsmlg_umbrella --version "$(cat ${CI_PROJECT_DIR}/releaseVersion)" --overwrite
    - cp -r _build/prod/rel/gsmlg_umbrella app
  artifacts:
    paths:
      - app

svc-build-image:
  dependencies:
    - svc-release
    - svc-build
  tags:
    - docker
    - linux
  stage: publish
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|beta|alpha)$/
      exists:
        - Dockerfile.lite
      changes:
        - "apps/gsmlg/**/*"
        - "apps/gsmlg_web/**/*"
        - "apps/gsmlg_admin_web/**/*"
        - "config/**/*"
        - "mix.*"
  image:
    name: ghcr.io/gsmlg-dev/kaniko-executor:debug
    entrypoint: [""]
  before_script:
    - echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
  script:
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile.lite \
        --destination "gsmlg.dev/apps/gsmlg:$(cat ${CI_PROJECT_DIR}/releaseVersion)" \
        --destination "gsmlg.dev/apps/gsmlg:latest" \
        --destination "docker.io/gsmlg/gsmlg-umbrella:v$(cat ${CI_PROJECT_DIR}/releaseVersion)" \
        --destination "docker.io/gsmlg/gsmlg-umbrella:latest" \
        --destination "ghcr.io/gsmlg-dev/gsmlg-umbrella:v$(cat ${CI_PROJECT_DIR}/releaseVersion)" \
        --destination "ghcr.io/gsmlg-dev/gsmlg-umbrella:latest"
