repositoryUrl: https://git.gsmlg.net/gsmlg/gsmlg_umbrella.git
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/gitlab"
    - "assets":
        - "CHANGELOG.md"
        - "mix.exs"
        - "apps/*/mix.exs"
  - - "@semantic-release/exec"
    - "prepareCmd": |
        echo "Next Version: ${nextRelease.version}"
        ./update_version.sh ${nextRelease.version}
      "publishCmd": |
        echo "${nextRelease.version}" | tee releaseVersion
branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - main
  - next
  - next-major
  - { name: "beta", prerelease: true }
  - { name: "alpha", prerelease: true }
