FROM gsmlg/alpine:latest

ARG RELEASE_VERSION=1.0.0

LABEL maintainer="Jonathan Gao <gsmlg.com@gmail.com>"
LABEL RELEASE_VERSION="${RELEASE_VERSION}"

ENV PORT=80 \
    REPLACE_OS_VARS=true \
    ERL_EPMD_PORT=4369 \
    POD_IP=127.0.0.1 \
    ERLCOOKIE=erlang_cookie \
    HOST=gsmlg.com \
    HOST_PORT=80 \
    DATABASE_URL=ecto://USER:PASS@HOST/DATABASE \
    POOL_SIZE=10 \
    SECRET_KEY_BASE=gsmlg_umbrella

ENV PATH=/app/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

COPY ./app /app

EXPOSE 80 4369

CMD ["/app/bin/gsmlg_umbrella", "start"]
