# Base configuration shared across all environments
# Values here can be overridden by environment-specific configs

[gsmlg]
mnesia_dir = ""

[logger]
log_level = "info"

[database]
username = "gsmlg_dev"
password = "gsmlg_dev"
hostname = "localhost"
database = "gsmlg_dev"
show_sensitive_data_on_connection_error = false
pool_size = 10

[web]
url = "http://localhost:4110"
port = 4110
user_register = false
enable_adsense = false
show_icp = false

[admin_web]
url = "http://localhost:4111"
port = 4111
user_register = false

[commander]
start = false
name = "commander"
platform_url = "ws://localhost:4111/commander-socket/websocket"

[oauth.github]
client_id = ""
client_secret = ""

[web_push]
subject = "mailto:administrator@example.com"
public_key = ""
private_key = ""
