import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :gsmlg_web, GSMLGWeb.Endpoint,
  url: [host: "gsmlg.org", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :gsmlg_admin_web, GSMLGAdminWeb.Endpoint,
  url: [host: "admin.gsmlg.org", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# CouchDB Server Connection, maybe use https in procution
config :gsmlg_couchdb, GSMLG.CouchDB.Connection, scheme: :http
