[gsmlg]
log_level = "debug"

[database]
username = "gsmlg_dev"
password = "gsmlg_dev"
hostname = "mariadb-server.gsmlg.net"
database = "gsmlg_dev"
show_sensitive_data_on_connection_error = true
pool_size = 10

[web]
url = "https://gsmlg.org"
secret_key_base = "o5xg8yDgSOFVrcrH4seZJ7+wJie4BHGOHmf9wP4mlhDFPPIqNETW8GU+gKVgrtFs"
port = 4110
user_register = false
enable_adsense = false
show_icp = false

[admin_web]
url = "https://admin.gsmlg.org"
secret_key_base = "o5xg8yDgSOFVrcrH4seZJ7+wJie4BHGOHmf9wP4mlhDFPPIqNETW8GU+gKVgrtFs"
port = 4111
user_register = false

[commander]
name = "commander"
platform_url = "https://commander.gsmlg.org"
platform_key = "o5xg8yDgSOFVrcrH4seZJ7+w"

[oauth.github]
client_id = ""
client_secret = ""

[web_push]
subject = "mailto:administrator@gsmlg.com"
public_key = "BIiu8m_dqtrKSvdquIqUJxsrkwswa0Zgep4myzmHlUcHjEtRdxdK4bZAEAd4dhFTARNGrbIkOJIcjdn13Z-yC4w"
private_key = "7mYUWrgUKIE_YGuFaIw2bRO0WjreR0iY6WoE7mDwbak"
