name: elixir-gsmlg-build-and-release
on:
  workflow_dispatch:
    inputs:
      release-version:
        required: true
        description: 'The version of the release'
        default: '4.21.0'
      revision:
        required: true
        description: 'The revision of git'
        default: 'main'

jobs:
  release:
    name: Create release ${{ github.event.inputs.release-version }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.semantic.outputs.revision }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: 💊 Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          elixir-version: "1.18.4"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 🚀 Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          MIX_ENV: prod
        run: |
          echo "release_verison = ${{ github.event.inputs.release-version }}"
          mix deps.get
          mix format --check-formatted

  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64 #,linux/arm64/v8
          push: true
          build-args: |
            NPM_CONFIG_REGISTRY=https://registry.npmjs.org/
            HEX_MIRROR=https://repo.hex.pm
            RELEASE_VERSION=${{ github.event.inputs.release-version }}
            DATABASE_URL=ecto://USER:PASS@HOST/DATABASE
          tags: |
            ghcr.io/gsmlg-dev/gsmlg-umbrella:v${{ github.event.inputs.release-version }}
            ghcr.io/gsmlg-dev/gsmlg-umbrella:latest

  build-package-amd64:
    name: Build otp relase package linux amd64
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 💊 Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          elixir-version: "1.18.4"

      - name: Setup zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          always-auth: true

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Deps
        run: |
          mix deps.get
          mix compile
          bun install
        env:
          MIX_ENV: prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: ⚙️ Run build
        env:
          MIX_ENV: prod
          RELEASE_NAME: gsmlg_umbrella
          RELEASE_VERSION: ${{ github.event.inputs.release-version }}
          DATABASE_URL: "ecto://USER:PASS@HOST/DATABASE"
        run: |
          cd ${{ github.workspace }}
          bash update_version.sh ${RELEASE_VERSION}
          mix prerelease
          mix release gsmlg_umbrella --version ${RELEASE_VERSION}
          mix release gsmlg_commander --version ${RELEASE_VERSION}
          cp -r _build/prod/rel/gsmlg_umbrella gsmlg
          tar zcf gsmlg.tar.gz gsmlg
          cp -r _build/prod/rel/gsmlg_commander commander
          tar zcf commander.tar.gz commander

      - name: ⬆️ Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.inputs.release-version }}
          file: "*.tar.gz"
          overwrite: true
          file_glob: true

